apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-hostnet-src
  template:
    metadata:
      labels:
        app: busybox-hostnet-src
    spec:
      hostNetwork: true
      containers:
        - name: busybox-deploy-pod
          image: busybox
          command:
            - sleep
            - "3600"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: true
            seLinuxOptions:
              level: "s0:c123,c456"
      nodeSelector:
        role: master
      tolerations:
      - key: "dedicated"
        operator: "Exists"
        effect: "NoSchedule"
