apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: busybox-daemonset
spec:
  selector:
    matchLabels:
      app: busybox-ds-ping
  template:
    metadata:
      labels:
        app: busybox-ds-ping
    spec:
      containers:
        - name: busybox-pod
          image: busybox
          command:
            - sleep
            - "3600"
      tolerations:
      - key: "dedicated"
        operator: "Exists"
        effect: "NoSchedule"
