apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod1
  labels:
    app: pingsrc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingsrc
  template:
    metadata:
      labels:
        app: pingsrc
    spec:
      containers:
      - name: busybox-pod
        image: busybox
        command:
        - sleep
        - "3600"
