apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod2
  labels:
    app: pingdst
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingdst
  template:
    metadata:
      labels:
        app: pingdst
    spec:
      containers:
      - name: busybox-pod
        image: busybox
        command:
        - sleep
        - "3600"
