---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    run: nginx
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: nginx
  selector:
    run: nginx
  type: NodePort
